version: '3'

services:
  django_backend:
    build:
      context: ./backend  # Path to your Django project's Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend  # Mount the Django project directory as a volume
    # environment:
    #   - DEBUG=1  # Set Django debug mode to true
    #   - SECRET_KEY=your_secret_key_here  # Replace with your Django secret key
    # depends_on:
    #   - db  # Depend on the database service
  
  react_frontend:
    build:
      context: ./frontend  # Path to your React.js project's Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend  # Mount the React.js project directory as a volume
    environment:
      - REACT_APP_API_URL=http://django_backend:8000/api  # Set the API URL to communicate with Django backend
    depends_on:
      - django_backend  # Depend on the Django service
  
  # db:
  #   image: postgres:latest
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_DB=mydatabase
  #     - POSTGRES_USER=myuser
  #     - POSTGRES_PASSWORD=mypassword
