### Create a new book ###

POST http://localhost:8000/api/books/
Content-Type: application/json

{
    "title": "Sample Book",
    "author": "John Doe",
    "publication_date": "2024-02-20"
}


### Retrieve all books ###

GET http://localhost:8000/api/books/


### Retrieve a specific book ###

GET http://localhost:8000/api/books/1/


### Update an existing book ###

PUT http://localhost:8000/api/books/1/
Content-Type: application/json

{
    "title": "Updated Book Title",
    "author": "Jane Smith",
    "publication_date": "2025-03-15"
}


### Delete a book ###

DELETE http://localhost:8000/api/books/1/
